controllers/planets_controller.py
import pdb
from flask import Flask, render_template, request, redirect
from flask import Blueprint
from models.planet import Planet
from models.visit import Visit
import repositories.planet_repository as planet_repository
import repositories.visit_repository as visit_repository
import repositories.user_repository as user_repository
import repositories.moon_repository as moon_repository

planets_blueprint = Blueprint("planets", __name__)

@planets_blueprint.route("/planets")
def planets():
    planets = planet_repository.select_all()
    moons = moon_repository.select_all_moons()
    user = user_repository.select_active_user()
    return render_template("planets/index.html", all_planets = planets, all_moons = moons, user = user)


@planets_blueprint.route("/planets/<id>", methods=['GET'])
def show_planet(id):
    planet = planet_repository.select(id)
    user = user_repository.select_active_user()
    moons = moon_repository.select_moons(id)
    visit_repository.save_visit(user, planet)
    user = user_repository.select_active_user()
    return render_template('planets/show.html', planet = planet, moons = moons, user = user) 


@planets_blueprint.route("/planets/new", methods=['GET'])
def new_planet():
    return render_template("planets/new.html")


@planets_blueprint.route("/planets",  methods=['POST']) 
def create_planet(): 
    name = request.form['name']   
    mass = request.form['mass']  
    temp = request.form['temp'] 
    gravity = request.form['gravity']
    image = request.form['image']
    description = request.form['description']
    planet = Planet(name, mass, temp, gravity, image, description) 
    planet_repository.save(planet)
    
    user = user_repository.select_active_user()
    visit_repository.save_visit(user, planet)
    visit = visit_repository.select_visit(user, planet)
    visit.mark_discovered()
    visit_repository.update_visit(visit)

    return redirect("/planets")


@planets_blueprint.route("/planets/<id>/edit", methods=['GET'])
def edit_planet(id):
    planet = planet_repository.select(id)
    return render_template('planets/edit.html', planet = planet)


@planets_blueprint.route("/planets/<id>", methods=['POST'])
def update_planet(id):
    name = request.form['name']
    mass = request.form['mass']
    temp = request.form['temp']
    gravity = request.form['gravity']
    image = request.form['image']
    description = request.form['description']
    new_planet = Planet(name, mass, temp, gravity, image, description)

    user = user_repository.select_active_user()
    planet_to_update = planet_repository.select(id)
    visit_to_update = visit_repository.select_visit(user, planet_to_update)
    visit_to_update.mark_altered()
    visit_to_update.location = new_planet.name
    visit_repository.update_visit(visit_to_update)
    planet_repository.update(new_planet)

    return redirect('/planets')


@planets_blueprint.route("/planets/<id>/delete", methods=['POST'])
def delete_planet(id):
    planet = planet_repository.select(id)
    user = user_repository.select_active_user()
    visit = visit_repository.select_visit(user, planet)
    visit.mark_destroyed()
    visit_repository.update_visit(visit)
    planet_repository.delete(id)

    return redirect('/planets')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://kit.fontawesome.com/cdc09b966c.js" crossorigin="anonymous"></script>
  <link href='https://fonts.googleapis.com/css?family=Roboto Condensed' rel='stylesheet'>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <title>Solar System</title>
</head>
<body class="home-body">
  <header>
    <nav class="base-menu">
      <h1 id="site-title">
        <a href="/planets">SOLAR SYSTEM.DB</a>
      </h1>
      <ul class="menu">
        <li><a href="/">Login</a></li>
        <li><a href="{{ url_for('planets.planets') }}">System </a></li>
        <li><a href="/exit">Exit</a></li>
      </ul>
    </nav>
  </header>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  <nav class="bottom">
    <a href="#site-title">Back to Top</a>
  </nav>
</body>
</html>

templates/exit.html
{% extends 'base.html' %}

{% block content %}

<div class="report">
    <h1>{{ user.name }}'s System Report</h1>

    {% if visits_total == 1%}
        <p class="visit-title">{{ visits_total }} Visit:</p>
    {% else %}
    <p class="visit-title">{{ visits_total }} Visits:</p>
    {% endif %}    
    <ul class="visits-list">
    {% for visit in visits %}
        <li>
        <p class="locations">{{ visit.location }}</p>
        </li>
    {% endfor %}
    </ul>

    <ul class="discoveries-list">
        {% if discovered_total == 1 %}
            <p>{{ discovered_total }} Discovery:</p>
        {% else %}
            <p>{{ discovered_total }} Discoveries:</p>
        {% endif %}
    {% for discovery in discoveries %}
        <li>
        <p class="locations"> {{ discovery.location }}</p>
        </li>
    {% endfor %}
    </ul>

    <ul class="alterations-list">
    {% if altered_total == 1 %}
        <p>{{ altered_total }} Edit:</p>
    {% else %}
        <p>{{ altered_total }} Edits:</p>
    {% endif %}
    {% for alteration in alterations %}
        <li>
        <p class="locations"> {{ alteration.location }}</p>
        </li>
    {% endfor %}
    </ul>

    <ul class="destructions-list">
    {% if destroyed_total == 1 %}
        <p>{{ destroyed_total }} Deletion:</p>
    {% else %}
        <p>{{ destroyed_total }} Deletions:</p>
    {% endif %}
    {% for destruction in destructions %}
        <li>
        <p class="locations"> {{ destruction.location }}</p>
        </li>
    {% endfor %}
    </ul>

</div>



    
{% endblock  %}

templates/index.html
{% extends "base.html" %}
{% block content %}

<section id="home-page">
  <div class="login-panel">
    <p>Existing User Login:</p>


    <div class="dropdown">
      <div class="users">
        {% for user in users %}
          <a href="/users/{{user.id}}">{{ user.name }} |</a>
        {% endfor %}
      </div>
    </div>
    <p>New User Login:</p>
    <form action="/" method="post">
        <label for="name"></label>
        <input type="text" id="name" name="name" placeholder="Name" required autofocus>
      <button type="submit">New User</button>
    </form>    
  </div>
</section>


{% endblock %}